from resources.health_check import HealthCheckResource
from resources.sample_entity import SampleEntityResource
from resources.customer import CustomerResource
from resources.health_check import HealthCheckResource
from resources.sample_entity import SampleEntityResource
from resources.accounts import AccountsResource
